Hacer que el script de atrapar al gato este mejor escrito
Dasher83/ChaosCats pull request #4
Opened 2023-08-27 20:18 UTC by Dasher83

2023-08-28 21:07 UTC, Yaukis requested changes

2023-08-28 21:07 UTC, Yaukis commented on Assets/Scripts/CatchCat.cs
> +        private bool IsInCathingRange => (player.transform.position - transform.position).magnitude < catchingDistance;
typo `IsInCathingRange` -> `isInCatchingRange`

2023-08-28 21:25 UTC, ZoomixZ approved these changes

2023-08-29 00:46 UTC, Dasher83 commented on Assets/Scripts/CatchCat.cs
> +        private bool IsInCathingRange => (player.transform.position - transform.position).magnitude < catchingDistance;
Gracias ahí lo arreglé

2023-08-30 02:40 UTC, Yaukis approved these changes

2023-08-30 02:57 UTC, merged